In [6]:
import numpy as np
import pandas as pd

In [7]:
df = pd.read_csv(r"C:\Users\LENOVO\Downloads\archive\WA_Fn-UseC_-HR-Employee-Attrition.csv")

In [8]:
df.info() # By using the df.info() we are here to check whether there any null value in the given dataset
          # we can see the result in console there no null value in the dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

In [9]:
df.duplicated().sum() #Here we are trying to find the duplicate values by using the in built funtion .duplicated()
                # here by add all the by using .sum() we can know the count of duplicate values

np.int64(0)

In [10]:
df["Age"].dtype #

dtype('int64')

### 1. Age Suspicion HR says: “We think young employees leave more.”
### Check ONLY:

### Age distribution
### Minimum, maximum, median
### How many employees are under 30?
### Find whether age could be a suspect.

In [11]:
df["Age"].value_counts()   # Here we are trying to figuring out no.of people according to the age group

Age
35    78
34    77
36    69
31    69
29    68
32    61
30    60
38    58
33    58
40    57
37    50
28    48
27    48
42    46
39    42
45    41
41    40
26    39
44    33
46    33
43    32
50    30
25    26
24    26
49    24
47    24
55    22
48    19
51    19
53    19
54    18
52    18
22    16
56    14
58    14
23    14
21    13
20    11
59    10
19     9
18     8
60     5
57     4
Name: count, dtype: int64

In [12]:
# Finding the clues in age column by univarate analysis
maximum = df["Age"].max()
print(maximum)   # Here we are try to figuring out what is the maximum age of a person in given dataset of age column

60

In [13]:
minimum = df["Age"].min()
print(minimum)    # Here we are try to figuring out what is the minimum age of a person in given dataset of age column

18

In [17]:
median = df["Age"].median()
print(median)   
print(minimum)    # Here we are try to figuring out what is the median age of a person in given dataset of age column

36.0
18

In [18]:
mask = df["Age"]<30
df["Age"][mask].value_counts() # Here we found that people age under 30 --- how many of them in their respective age group

Age
29    68
27    48
28    48
26    39
25    26
24    26
22    16
23    14
21    13
20    11
19     9
18     8
Name: count, dtype: int64

### 2. Income Mystery : Finance team believes members with lower income are unhappy.

### Your task:

### Check average, median, quartiles of MonthlyIncome.
### Is income skewed? – describe()
### Do you see many employees earning at the lower end

In [19]:
mean = df["MonthlyIncome"].mean().round(3)
print(mean)      # In the second question we are checking out the mean value of monthlyincome column 
                 # so that we can know the average income of the group

6502.931

In [20]:
median = df["MonthlyIncome"].median()
print(median)

4919.0

In [21]:
df["MonthlyIncome"].describe()

count     1470.000000
mean      6502.931293
std       4707.956783
min       1009.000000
25%       2911.000000
50%       4919.000000
75%       8379.000000
max      19999.000000
Name: MonthlyIncome, dtype: float64

In [22]:
print("the quartiles of MonthlyIncome at 25% is ",df["MonthlyIncome"].describe()["25%"])
print("the quartiles of MonthlyIncome at 50% is ",df["MonthlyIncome"].describe()["50%"])
print("the quartiles of MonthlyIncome at 75% is ",df["MonthlyIncome"].describe()["75%"])

the quartiles of MonthlyIncome at 25% is  2911.0
the quartiles of MonthlyIncome at 50% is  4919.0
the quartiles of MonthlyIncome at 75% is  8379.0

In [23]:
# is income skewed? – describe()

# here we figure out that data of MonthlyIncome is skewed towards rightside so it positive skew

In [24]:
mask1 = df["MonthlyIncome"]< mean
df["MonthlyIncome"][mask1].value_counts()   # here we are found that no.of persons MonthlyIncome of employees 
                                            # earning at the lower end which below the mean(average)

MonthlyIncome
2342    4
2741    3
3452    3
2610    3
2559    3
       ..
3785    1
2966    1
2571    1
5390    1
3944    1
Name: count, Length: 865, dtype: int64

### 3. Distance-from-Home Rumor

### Someone said: "People who live far leave the company."

### Check percentiles of DistanceFromHome.
### Identify if there are many long commuters. → quantile | skewness

In [25]:
df["DistanceFromHome"].describe()

count    1470.000000
mean        9.192517
std         8.106864
min         1.000000
25%         2.000000
50%         7.000000
75%        14.000000
max        29.000000
Name: DistanceFromHome, dtype: float64

In [26]:
print("the percentiles of DistanceFromHome 25% ",df["DistanceFromHome"].describe()["25%"])
print("the percentiles of DistanceFromHome 50% ",df["DistanceFromHome"].describe()["50%"])
print("the percentiles of DistanceFromHome 75% ",df["DistanceFromHome"].describe()["75%"])

the percentiles of DistanceFromHome 25%  2.0
the percentiles of DistanceFromHome 50%  7.0
the percentiles of DistanceFromHome 75%  14.0

In [27]:
# Here we identify that most of people are long commuters

### 4. OverTime Alarm

### Count how many people have OverTime = Yes vs No.
### Is OverTime common or rare?
### This is a major future suspect.

In [28]:
df["OverTime"].value_counts()
# here most of the people not doing the OverTime

OverTime
No     1054
Yes     416
Name: count, dtype: int64

In [29]:
# Is OverTime common or rare? 
#  here OverTime is rare because majority of the people don't do OverTime

In [30]:
# right now we can't say it is a major suspect because most of the people don't do the OverTime 
# more 25%

### 5. Job Role Hotspot

### Find top 3 JobRoles by population.
### This tells you where most attrition could happen.

In [31]:
df["JobRole"].value_counts()
# here we can see that the top 3 jobroles by population are 1. Sales Executive
                                                          # 2. Research Scientist
                                                          # 3. Laboratory Technician

JobRole
Sales Executive              326
Research Scientist           292
Laboratory Technician        259
Manufacturing Director       145
Healthcare Representative    131
Manager                      102
Sales Representative          83
Research Director             80
Human Resources               52
Name: count, dtype: int64

 ## BIVARIATE ANALYSIS INTERPRETATION`

### 6. The OverTime-Attrition Interrogation

### HR claims: “OverTime increases Attrition.”

### Use crosstab with normalize to check if:
### Attrition% is higher in OverTime = Yes.

In [32]:
pd.crosstab(df["OverTime"],df["Attrition"],normalize='index').round(2) 
#pd.crosstab(df["OverTime"],df["Attrition"])
            
# the highest no.of people dont do the OverTime but,
# if you seen the table below the most of people who took the attrition is the one who works OverTime 
# here we can see total people who do OverTime is 416 in this 127 members which is 30% them are quit
# and people who don't do OverTime is 1054 in this 110 member which is 10% of them are quit 
# from this we can say that Attrition % is higher in OverTime  
# Attrition rate is 20 % more than in OverTime
# OverTime looks like a prime suspect. Employees who do overtime have a 45% quitting rate — nearly quadruple the rate of those who don't.
# This suggests workload pressure or burnout.

Attrition    No   Yes
OverTime
No         0.90  0.10
Yes        0.69  0.31

### 7. The Travel Conspiracy

### Managers think frequent travelers quit more.
### Use crosstab (normalize row-wise): BusinessTravel vs Attrition
### Which travel group seems most suspicious?

In [33]:
pd.crosstab(df["BusinessTravel"],df["Attrition"])

Attrition           No  Yes
BusinessTravel
Non-Travel         138   12
Travel_Frequently  208   69
Travel_Rarely      887  156

In [34]:
# In this analysis, we can understand that there are a total of 1469 persons 
# in these 1469 persons # Travel_Rarely  # Travel_Frequently # Non- Travel
# from the total of 1469 - 237 persons, which is 16% of which 65% --> 156 are attriting, mostly are from the Travel_rarrly group
# The Travel_Rarely group seems more suspicious because maybe they won't get the opportunity to move around like others

### 8.The Department Discrepancy

### Use groupby: Department → mean MonthlyIncome
### Which department might be underpaid?
### Could that explain Attrition?

In [35]:
df.groupby(["Department","Attrition"])["MonthlyIncome"].agg(["mean"]).round(2)

                                     mean
Department             Attrition
Human Resources        No         7345.98
                       Yes        3715.75
Research & Development No         6630.33
                       Yes        4108.08
Sales                  No         7232.24
                       Yes        5908.46

In [36]:
# In the above analysis, we can find a pattern.
# A possible reason behind this pattern is that the people leaving the organisation is they are underpaid. 
# Why are they underpaid? And the difference is almost 50% in each department, so it should be figured out

### 9. Gender Bias Check

### Check:
## Gender vs Attrition (crosstab %)
### Is there any surprising bias?

In [37]:
pd.crosstab(df["Gender"],df["Attrition"])

Attrition   No  Yes
Gender
Female     501   87
Male       732  150

In [38]:
# In the above analysis, we can see that there are nearly 20% of people leaving in both groups 
# It's almost the same percentage, so nothing surprising bias

### 10. JobSatisfaction Leak

### Check average JobSatisfaction per JobRole. 
### Which JobRole has lowest satisfaction?
### Possible motive for quitting.

In [39]:
pd.crosstab(df["JobRole"],df["JobSatisfaction"])

JobSatisfaction             1   2   3    4
JobRole
Healthcare Representative  26  19  43   43
Human Resources            10  16  13   13
Laboratory Technician      56  48  75   80
Manager                    21  21  27   33
Manufacturing Director     26  32  49   38
Research Director          15  16  27   22
Research Scientist         54  53  90   95
Sales Executive            69  54  91  112
Sales Representative       12  21  27   23

In [40]:
# In the above average jobsatisfaction per jobrole we can see the pattern that in every JobRole, there is an average 16 - 20% JobSatifaction level of 1
# From this we can know that there is a very good chance These people can Attrirate

In [41]:
df.groupby("JobRole")["JobSatisfaction"].mean()

JobRole
Healthcare Representative    2.786260
Human Resources              2.557692
Laboratory Technician        2.691120
Manager                      2.705882
Manufacturing Director       2.682759
Research Director            2.700000
Research Scientist           2.773973
Sales Executive              2.754601
Sales Representative         2.734940
Name: JobSatisfaction, dtype: float64

### MULTIVARIATE ANALYSIS

### 11. Triple Threat Case

### People say Attrition happens when Age is low, Income is low, and Satisfaction is low.

### Use filtering:
### Age < 30
### MonthlyIncome < median
### JobSatisfaction < median
### How many such “high risk” employees exist?

In [42]:
df[(df["Age"]<30) & (df["MonthlyIncome"]<df["MonthlyIncome"].median()) & (df["JobSatisfaction"]<df["JobSatisfaction"].median())]

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
41,27,No,Travel_Rarely,1240,Research & Development,2,4,Life Sciences,1,54,...,4,80,1,1,6,3,1,0,0,0
71,29,No,Travel_Rarely,1328,Research & Development,2,3,Life Sciences,1,94,...,4,80,1,6,3,3,5,4,0,4
86,23,No,Travel_Rarely,541,Sales,2,1,Technical Degree,1,113,...,3,80,1,3,3,3,0,0,0,0
125,26,No,Travel_Rarely,841,Research & Development,6,3,Other,1,164,...,3,80,0,5,3,2,5,4,4,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1411,25,No,Travel_Rarely,309,Human Resources,2,3,Human Resources,1,1987,...,3,80,0,6,3,3,2,0,1,2
1436,21,No,Travel_Rarely,501,Sales,5,1,Medical,1,2021,...,4,80,0,2,6,3,2,2,1,2
1438,23,Yes,Travel_Frequently,638,Sales,9,3,Marketing,1,2023,...,1,80,1,1,3,2,1,0,1,0
1459,29,No,Travel_Rarely,1378,Research & Development,13,2,Other,1,2053,...,1,80,1,10,2,3,4,3,0,3
1460,29,No,Travel_Rarely,468,Research & Development,28,4,Medical,1,2054,...,2,80,0,5,3,1,5,4,0,4

In [43]:
(106/1470)*100

7.210884353741497

In [44]:
arr = np.where((df["Age"]<30) & (df["MonthlyIncome"]<df["MonthlyIncome"].median()) & (df["JobSatisfaction"]<df["JobSatisfaction"].median()),"triple","others")

In [45]:
pd.crosstab(arr,df["Attrition"],normalize="index").round(2)

Attrition    No   Yes
row_0
others     0.85  0.15
triple     0.64  0.36

In [46]:
# In here we can find people with low income, the least jobSatisfaction and age below 30 is only 7%

# The combination of Age and MonthlyIncome,JobSatisfaction, along with Attrition 
# this significantly increased to 21 % by subtracting triple treat with others 
# With this analysis we can know that when income is low, jobsatisfaction is low in people below 30 leaves the Organization

### 12. Department x JobRole Investigation

### Group by: Department, JobRole → Attrition count

### Which combinations show high exits?

In [47]:
df.groupby(["Department","JobRole"])["Attrition"].value_counts()

Department              JobRole                    Attrition
Human Resources         Human Resources            No            40
                                                   Yes           12
                        Manager                    No            11
Research & Development  Healthcare Representative  No           122
                                                   Yes            9
                        Laboratory Technician      No           197
                                                   Yes           62
                        Manager                    No            51
                                                   Yes            3
                        Manufacturing Director     No           135
                                                   Yes           10
                        Research Director          No            78
                                                   Yes            2
                        Research Scientist         No           245
                                                   Yes           47
Sales                   Manager                    No            35
                                                   Yes            2
                        Sales Executive            No           269
                                                   Yes           57
                        Sales Representative       No            50
                                                   Yes           33
Name: count, dtype: int64

In [48]:
# Here after doing some analysis by groupby and value_counts, we found that the highest attritions is in 
# Research & Development - Labortory Technician ---> 62
#                          Research Scientist ---> 47
# Sales - Sales Executive   --> 57 
#         Sales Representative --> 33 
# HR - HR --> 12
# These are HotSpots we can in this analysis 
# The combination we can find high in Research & Development X Laboratory Technician

### 13. Salary Ladder Case

### Use pivot table:
### JobLevel × EducationField → mean MonthlyIncome
### Which combination earns the most
### Which earns the least?
### This reveals potential compensation unfairness.

In [50]:
# The combination that earns the most is in EducationField X TechnicalDegree in JobLevel = "5" --- 19573
# The combination that earns the least is in EducationField X Human Resources in JobLevel = "1" --- 2564
# "Yes" This reveals potential compensation and unfairness is seen in the JobLevel '1' and '4' is around 15%

### 14. The Long Commute Problem

### Multivariate check: 
### DistanceFromHome + OverTime + Attrition

### Find:
### Among employees who do OverTime AND live > 10 km, how many left?
### This is detective-level bivariate + filter logic.

In [ ]:
df[ (df["OverTime"] == "Yes") & (df["DistanceFromHome"]>10) & (df["Attrition"]=="Yes")].shape

(55, 35)

In [61]:
(55/1470)*100

3.741496598639456

In [62]:
# In total no.of employees who do OverTime and live > 10km raidus and left the organization are 55 members 
# which is 3.7% of total members

### 15. Lifestyle Breakdown Case

### Group by Department:

### Avg WorkLifeBalance
### Avg JobSatisfaction
### Attrition count
### Which department seems “stressful”?

In [63]:
pd.pivot_table(df,index=["Department"],values=["WorkLifeBalance","JobSatisfaction"],aggfunc="mean").round(2)

                        JobSatisfaction  WorkLifeBalance
Department
Human Resources                    2.60             2.92
Research & Development             2.73             2.73
Sales                              2.75             2.82

In [72]:
pd.crosstab(df["Department"],df["Attrition"])

Attrition                No  Yes
Department
Human Resources          51   12
Research & Development  828  133
Sales                   354   92

In [73]:
# Lifestyle Breakdown Case
# Avg WorkLifeBalance
# Avg JobSatisfaction
# Attrition count
# by all this department the stressful on is the Research & Development because it has more no.of Attrition 133 which is 16%

### FINAL SUSPECT IDENTIFICATION

In [74]:
# 16. Who are the top 3 strongest suspects causing Attrition?


# The first strongest suspect causing Attrition is OverTime because people are leaving more than 25%  
# THE second strongest suspect causing Attrition is Potential compensation, the difference between JobLevel 1 and 4 
# and Unfairness, which is 15%
# The third Strongest suspect causing Attrition is  people with low Income and people with low Satisfaction level is 7%

In [75]:
#  17. Which groups of employees face the highest quitting risk

# the groups of employees face the highest quitting risk is :
# Sales Representatives and Laboratory Technicians
# younger employees age less than 30 years
# Lower-income level 
# Low JobSatisfaction scores are 1–2

In [76]:
# 18. Which department needs immediate HR intervention? Why?

# The department needs immediate HR intervention is Sales Representatives and Laboratory Technicians shows the highest attrition rates.
# Lower-income level individuals face a higher quitting risk.
# When MonthlyIncome is below the median, attrition percentages of Attrition rises significantly.

In [77]:
# 19. What patterns suggest workload issues?

# the patterns suggest workload issues is OverTime and Attrition
# WorkLifeBalance ratings of low level 1 and 2
# lowSatisfaction in specific roles 
# below 30 aged and lower income people

In [78]:
# 20. Give 5 actionable recommendations based on your investigation.

# addressing the Overtime and workload issue by redistributing the workload 
# improve the Jobsatisfaction level by conducting surveys and taking feedbacks from the employees
# Mentoring the younger people 
# by increasing wages based on the performance
# maintaining the worklifebalance by offer wellness programs and flexiable work timings and by monitoring the wellsness of employess